#!/bin/bash

CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 GOPATH=/home/ana/whitehat-security-code/build/gopath PATH=/home/ana/whitehat-security-code/build/gopath/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin packr build -a -tags netgo -ldflags="-w -extldflags "-static" -X main.VersionString=0.2" -o bin/whitehat.q
CGO_ENABLED=0 GOOS=linux GOARCH=386 GOPATH=/home/ana/whitehat-security-code/build/gopath PATH=/home/ana/whitehat-security-code/build/gopath/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin packr build -a -tags netgo -ldflags="-w -extldflags "-static" -X main.VersionString=0.2" -o bin/whitehat.w
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GOPATH=/home/ana/whitehat-security-code/build/gopath PATH=/home/ana/whitehat-security-code/build/gopath/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin packr build -a -tags netgo -ldflags="-w -extldflags "-static" -X main.VersionString=0.2" -o bin/whitehat.e
CGO_ENABLED=0 GOOS=linux GOARCH=arm GOPATH=/home/ana/whitehat-security-code/build/gopath PATH=/home/ana/whitehat-security-code/build/gopath/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin packr build -a -tags netgo -ldflags="-w -extldflags "-static" -X main.VersionString=0.2" -o bin/whitehat.r
CGO_ENABLED=0 GOOS=linux GOARCH=arm64 GOPATH=/home/ana/whitehat-security-code/build/gopath PATH=/home/ana/whitehat-security-code/build/gopath/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin packr build -a -tags netgo -ldflags="-w -extldflags "-static" -X main.VersionString=0.2" -o bin/whitehat.t
CGO_ENABLED=0 GOOS=linux GOARCH=mips GOPATH=/home/ana/whitehat-security-code/build/gopath PATH=/home/ana/whitehat-security-code/build/gopath/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin packr build -a -tags netgo -ldflags="-w -extldflags "-static" -X main.VersionString=0.2" -o bin/whitehat.y
CGO_ENABLED=0 GOOS=linux GOARCH=mips GOPATH=/home/ana/whitehat-security-code/build/gopath PATH=/home/ana/whitehat-security-code/build/gopath/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin packr build -a -tags netgo -ldflags="-w -extldflags "-static" -X main.VersionString=0.2" -o bin/whitehat.u
CGO_ENABLED=0 GOOS=linux GOARCH=mipsle GOPATH=/home/ana/whitehat-security-code/build/gopath PATH=/home/ana/whitehat-security-code/build/gopath/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin packr build -a -tags netgo -ldflags="-w -extldflags "-static" -X main.VersionString=0.2" -o bin/whitehat.i
CGO_ENABLED=0 GOOS=linux GOARCH=mips64 GOPATH=/home/ana/whitehat-security-code/build/gopath PATH=/home/ana/whitehat-security-code/build/gopath/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin packr build -a -tags netgo -ldflags="-w -extldflags "-static" -X main.VersionString=0.2" -o bin/whitehat.o
CGO_ENABLED=0 GOOS=linux GOARCH=mips64le GOPATH=/home/ana/whitehat-security-code/build/gopath PATH=/home/ana/whitehat-security-code/build/gopath/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin packr build -a -tags netgo -ldflags="-w -extldflags "-static" -X main.VersionString=0.2" -o bin/whitehat.p
CGO_ENABLED=0 GOOS=freebsd GOARCH=386 GOPATH=/home/ana/whitehat-security-code/build/gopath PATH=/home/ana/whitehat-security-code/build/gopath/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin packr build -a -tags netgo -ldflags="-w -extldflags "-static" -X main.VersionString=0.2" -o bin/whitehat.a
CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 GOPATH=/home/ana/whitehat-security-code/build/gopath PATH=/home/ana/whitehat-security-code/build/gopath/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin packr build -a -tags netgo -ldflags="-w -extldflags "-static" -X main.VersionString=0.2" -o bin/whitehat.s
CGO_ENABLED=0 GOOS=windows GOARCH=386 GOPATH=/home/ana/whitehat-security-code/build/gopath PATH=/home/ana/whitehat-security-code/build/gopath/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin packr build -a -tags netgo -ldflags="-w -extldflags "-static" -X main.VersionString=0.2" -o bin/whitehat.d
CGO_ENABLED=0 GOOS=windows GOARCH=amd64 GOPATH=/home/ana/whitehat-security-code/build/gopath PATH=/home/ana/whitehat-security-code/build/gopath/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin packr build -a -tags netgo -ldflags="-w -extldflags "-static" -X main.VersionString=0.2" -o bin/whitehat.f
